# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGorUser\User\Domain\Model\UserGuest:
    type: mappedSuperclass
    repositoryClass: BenGorUser\DoctrineORMBridge\Infrastructure\Persistence\DoctrineORMUserGuestRepository
    table: user_guest
    id:
        id:
            column: id
            type: user_guest_id
    embedded:
        email:
            class: BenGorUser\User\Domain\Model\UserEmail
            columnPrefix: false
        invitationToken:
            class: BenGorUser\User\Domain\Model\UserToken
            columnPrefix: invitation_
    fields:
        createdOn:
            column: created_on
            type: datetime
